spring:
    profiles:
        active:
        - dev      
---
spring:
    proflies: dev #开发环境
    application:
        name: microservicecloud-config-atguigu-dev
---
spring:
    proflies: test #测试环境
    application:
        name: microservicecloud-config-atguigu-test