spring:
    profiles:
        active:
        - dev      
---
server:
    port: 8201
spring:
    proflies: dev #开发环境
    application:
        name: microservicecloud-config-client
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
---
server:
    port: 8202
spring:
    proflies: test #测试环境
    application:
        name: microservicecloud-config-client
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/